name: Package and Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GITHUB_OAUTH: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Project
        uses: actions/checkout@main

      - name: Package AddOns
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

          zip -r "71_Porn-${{env.TAG_NAME}}.zip" . -x "*.git*"

      - name: Release AddOns
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{env.TAG_NAME}}
          files: ./*.zip
          body: |
            不要问，更就完事了！
