name: Package and Release

on:
  push:
    tags:
      - 'v*.*.*'

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

permissions: write-all

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Releases
        uses: dev-drprasad/delete-older-releases@master
        with:
          keep_latest: 1
          delete_tags: true

      - name: Delete Old Workflows
        uses: Mattraks/delete-workflow-runs@main
        with:
          retain_days: 0
          keep_minimum_runs: 1

  release:
    runs-on: ubuntu-latest
    needs: cleanup
    steps:
      - name: Clone Project
        uses: actions/checkout@main

      - name: Package AddOns
        run: |
          echo "TAG_NAME=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

          zip -r "71_AddOns-${GITHUB_REF#refs/tags/}.zip" . -x "*.git*"

      - name: Release AddOns
        uses: softprops/action-gh-release@master
        with:
          tag_name: ${{env.TAG_NAME}}
          files: ./*.zip
          body: |
            不要问，更就完事了！
